### ISSUE TITLE
Color problem in Javascript

### ISSUE THREAD

**Issue by sefechit** [franbach/miramare#1]
![Screenshot from 2020-04-06 11-57-23](https://user-images.githubusercontent.com/44240685/78541840-ef651880-77fe-11ea-98df-9c0d63f2501d.png)

Hello,
Firstly, just wanted to say that I love your scheme, somewhat underrated, so thank you for that :)
Secondly, the problem in the picture is that the 2 function arguments have different colors, the first has the blue and the second has the LightGrey.

When executing the command:
```
:echo synIDattr(synID(line("."), col("."), 1), "name")
```

The first argument returns 'jsParen' (weird) and the second returns 'jsFutureKeys'.

Are you familiar with the problem?

Btw, regardless to the above-mentioned issue, I recommend that you change the jsTemplateExpression color to LightGrey instead of Yellow, looks much nicer IMO, changed that locally already :)

**Comment by franbach** [comment]
Hello mectos!
Thanks for the detailed explanation! 
I've modified the color in jsTemplateExpression as you mentioned :)
About the error, I'm not familiar with it. Feel free to fix it!
cheers!

**Comment by franbach** [comment]
Hello @mectos!
I'm glad you liked it! Thanks for the detailed explanation!
I've modified the color in jsTemplateExpression as you mentioned :)
About the error, I'm not familiar with it. Feel free to fix it!
cheers!
