### ISSUE TITLE
Missing error and warning colors on airline/lightline

### ISSUE THREAD

**Issue by oblitum** [franbach/miramare#18]
No error/warning colors for airline/lightline are being provided (I use lightline), it would be nice to have, example: https://github.com/tyrannicaltoucan/vim-deep-space/blob/master/autoload/lightline/colorscheme/deepspace.vim#L26-L27

**Comment by FrenzyExists** [comment]
I think this repo is dead :\

**Comment by FrenzyExists** [comment]
Good news, its merged!!!!

**Comment by oblitum** [comment]
Well, I'll close it, though I don't use it anymore as I'm using lualine these days...
