### ISSUE TITLE
Contrast too low on comments & selection

### ISSUE THREAD

**Issue by GitSquared** [franbach/miramare#2]
Hey, thanks for this great theme!

I really like the colors but I find it super difficult to read code comments, and see my current selection. There is not enough contrast with the background.

![Screenshot_20200423_112015](https://user-images.githubusercontent.com/24496417/80082279-69620500-8554-11ea-8c12-eb14ec1112a1.png)

It helps to up my screen's brightness to 100% but that's not viable. I have an OLED display, so it might be that the already-low contrast on those colors is accentuated by black crushing.

**Comment by franbach** [comment]
Hey @GitSquared! Yep, I noticed too! I'm bit busy right now, but I'm going to have a look on that, for sure. Thanks for the feedback!

**Comment by GitSquared** [comment]
Great! I might have some time this weekend to look into this. I'll send you a PR, if that doesn't bother you.

**Comment by franbach** [comment]
@GitSquared sure! no problem! 😉🤜

**Comment by GitSquared** [comment]
:fist_left::wink: #3
